import { ArrowDownRight, ArrowRight, ArrowUpRight, Boxes, CircleDollarSign, Clock3, PackageCheck, Plus, ShoppingBag, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAdminData } from '../features/admin/AdminDataContext';
import { PageTitle, StatusPill } from '../features/admin/AdminShared';
import { useCurrency } from '../features/currency/CurrencyContext';

export function AdminDashboard() {
  const { formatPrice } = useCurrency();
  const { products, orders, customers } = useAdminData();
  const activeProducts = products.filter((product) => product.status === 'Active').length;
  const lowStock = products.filter((product) => product.stock <= 10 && product.status === 'Active').length;
  const pendingOrders = orders.filter((order) => order.status === 'Pending').length;
  const totalRevenue = orders.filter((order) => order.status !== 'Cancelled').reduce((sum, order) => sum + order.total, 0);
  const metrics = [
    { label: 'Total products', value: products.length, icon: Boxes, note: 'Across all categories', tone: 'sand' },
    { label: 'Active products', value: activeProducts, icon: PackageCheck, note: `${products.length - activeProducts} inactive`, tone: 'sage' },
    { label: 'Low stock', value: lowStock, icon: ArrowDownRight, note: '10 units or fewer', tone: 'rose' },
    { label: 'Total orders', value: orders.length, icon: ShoppingBag, note: `${pendingOrders} need attention`, tone: 'blue' },
  ];
  return <div className="admin-page"><PageTitle eyebrow="Thursday, October 1" title="Good morning, Vera" description="Here’s what’s happening with your store today." action={<Link to="/admin/products/new" className="admin-primary-button"><Plus size={16} /> Add product</Link>} />
    <section className="admin-metrics">{metrics.map(({ label, value, icon: Icon, note, tone }) => <article className="admin-metric-card" key={label}><div className={`metric-icon ${tone}`}><Icon size={18} strokeWidth={1.7} /></div><span className="metric-note">{note}</span><strong>{value}</strong><span className="metric-label">{label}</span></article>)}</section>
    <section className="admin-dashboard-grid"><article className="admin-panel revenue-panel"><div className="panel-header"><div><span className="admin-eyebrow">Store snapshot</span><h2>Sales overview</h2></div><span className="panel-date">Last 7 days <ArrowDownRight size={14} /></span></div><div className="revenue-total"><strong>{formatPrice(totalRevenue)}</strong><span className="revenue-change"><ArrowUpRight size={14} /> 12.8%</span><small>Mock order revenue to date</small></div><div className="mini-chart" aria-label="Illustrative weekly sales chart"><div className="chart-y-labels"><span>{formatPrice(1000)}</span><span>{formatPrice(750)}</span><span>{formatPrice(500)}</span><span>{formatPrice(250)}</span><span>{formatPrice(0)}</span></div><div className="chart-plot"><div className="chart-gridlines"><i /><i /><i /><i /><i /></div><div className="chart-bars">{[['M',42],['T',61],['W',49],['T',76],['F',58],['S',90],['S',69]].map(([day,height],index)=><div className="chart-day" key={`${day}-${index}`}><span style={{height:`${height}%`}} className={index===5?'bar-highlight':''} /><small>{day}</small></div>)}</div></div></div></article>
      <article className="admin-panel order-glance"><div className="panel-header"><div><span className="admin-eyebrow">Needs a little love</span><h2>Order pulse</h2></div><Clock3 size={17} className="subtle-icon" /></div><div className="order-pulse-number"><strong>{pendingOrders.toString().padStart(2,'0')}</strong><span>orders to review</span></div><p>Take a look at the latest orders and keep things moving.</p><Link to="/admin/orders" className="admin-text-link">View all orders <ArrowRight size={14} /></Link><div className="pulse-divider" /><div className="pulse-summary"><span><span className="pulse-dot dot-pending" />Pending</span><strong>{pendingOrders}</strong></div><div className="pulse-summary"><span><span className="pulse-dot dot-processing" />Processing</span><strong>{orders.filter((order)=>order.status==='Processing').length}</strong></div><div className="pulse-summary"><span><span className="pulse-dot dot-delivered" />Delivered</span><strong>{orders.filter((order)=>order.status==='Delivered').length}</strong></div></article>
    </section>
    <section className="admin-dashboard-grid bottom-dashboard-grid"><article className="admin-panel recent-orders-panel"><div className="panel-header"><div><span className="admin-eyebrow">Fresh from the shop</span><h2>Recent orders</h2></div><Link to="/admin/orders" className="admin-text-link">All orders <ArrowRight size={14} /></Link></div><div className="recent-order-list">{orders.slice(0,4).map((order)=><div className="recent-order-row" key={order.id}><div className="recent-order-avatar">{order.customer.split(' ').map(part=>part[0]).join('')}</div><div className="recent-order-person"><strong>{order.customer}</strong><span>{order.id} · {order.items.reduce((n,item)=>n+item.quantity,0)} items</span></div><StatusPill status={order.status} /><strong className="recent-order-total">{formatPrice(order.total)}</strong></div>)}</div></article><article className="admin-panel recent-products-panel"><div className="panel-header"><div><span className="admin-eyebrow">In your collection</span><h2>Recent products</h2></div><Link to="/admin/products" className="admin-text-link">All products <ArrowRight size={14} /></Link></div><div className="recent-product-list">{products.slice(0,4).map((product)=><div className="recent-product-row" key={product.id}><div className="recent-product-swatch" style={{backgroundImage:`url(${product.images[0] ?? ''})`}} /><div><strong>{product.name}</strong><span>{product.category} · {product.stock} in stock</span></div><span className="recent-product-price">{formatPrice(product.price)}</span></div>)}</div></article></section>
    <div className="admin-dashboard-bottom-note"><span><Users size={15} /> {customers.length} customers in your preview</span><span><CircleDollarSign size={15} /> No live transactions</span></div>
  </div>;
}
