import { ArrowDown, ArrowRight, ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { brand } from '../config/brand';
import { categories } from '../data/products';
import { ProductGrid } from '../components/ProductGrid';
import { useCatalog } from '../features/catalog/CatalogContext';

export function HomePage() {
  const { products } = useCatalog();
  return <>
    <section className="hero-section"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-dot" /> The new season, considered</span><h1>Wear the feeling<br /><em>of being yourself.</em></h1><p>Thoughtful shapes, beautiful textures, and the pieces you reach for again and again.</p><Link to="/shop" className="button button-primary hero-cta">Discover the collection <ArrowRight size={16} /></Link><div className="hero-note"><span>01 / 03</span><span className="hero-note-line" /><span>New season essentials</span></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1800&q=90" alt="Model wearing understated neutral fashion against a warm backdrop" /><div className="hero-image-caption"><span>THE ART OF EVERYDAY</span><span>SS / 25</span></div><div className="hero-stamp">Made for<br />your moments</div></div><a href="#featured" className="scroll-cue" aria-label="Scroll to featured pieces"><ArrowDown size={14} /> Scroll to explore</a></section>
    <section className="intro-band"><span className="eyebrow">A wardrobe with intention</span><p>Less, but <em>better.</em> VERA is a study in ease — pieces that feel like you, only a little more <em>you.</em></p><span className="intro-signature">{brand.name} — Est. in the everyday</span></section>
    <section className="section-wrap featured-section" id="featured"><div className="section-heading"><div><span className="eyebrow">Good things, lately</span><h2>Pieces to keep close</h2></div><Link className="text-link" to="/shop">Shop all pieces <ArrowUpRight size={15} /></Link></div><ProductGrid products={products.filter((product) => product.featured).slice(0, 4)} /></section>
    <section className="category-section" id="collections"><div className="section-wrap"><div className="section-heading"><div><span className="eyebrow">Find your feeling</span><h2>Explore the collection</h2></div><p>Everyday favorites, thoughtfully made<br />for wherever the day takes you.</p></div><div className="category-grid">{categories.map((category, index) => <Link to={`/shop?category=${encodeURIComponent(category.name)}`} className={`category-tile category-tile-${index + 1}`} key={category.name}><img src={category.image} alt={`${category.name} collection`} loading="lazy" /><div className="category-overlay"><span>{category.countLabel}</span><h3>{category.name}</h3><span className="category-arrow"><ArrowUpRight size={17} /></span></div></Link>)}</div></div></section>
    <section className="story-cta"><div className="story-image"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1300&q=85" alt="A quiet moment from the VERA CLOTHING collection" loading="lazy" /></div><div className="story-content"><span className="eyebrow">Our point of view</span><h2>Good clothes should feel like <em>coming home.</em></h2><p>Designed around real life, made with a little more care. Meet the pieces that make getting dressed feel easy.</p><Link to="/shop" className="button button-primary">Find your everyday <ArrowRight size={16} /></Link></div></section>
    <section className="newsletter-band"><span className="eyebrow">The VERA point of view</span><h2>Find your kind of everyday.</h2><p>Keep the things you love close. Let the rest feel easy.</p><Link to="/shop" className="text-link">Explore the collection <ArrowRight size={15} /></Link></section>
  </>;
}
